yarnPath: .yarn/releases/yarn-3.2.2.cjs
nodeLinker: ${NODE_LINKER:-pnp}

enableScripts: true

packageExtensions:
  "gatsby@*":
    dependencies:
      "babel-plugin-import": "*"
  "@sentry/gatsby@*":
    dependencies:
      "tslib": "*"
  "@splitsoftware/splitio-react@*":
    dependencies:
      "tslib": "*"
  "react-dnd@*":
    dependencies:
      "@react-dnd/invariant": "*"
  "tss-react@*":
    dependencies:
      "@mui/material": "*"
  "react-draft-wysiwyg@*":
    dependencies:
      "draft-js": "*"
      "immutable": "*"
  "mui-phone-input-ssr@*":
    dependencies:
      "clsx": "*"
      "@material-ui/core": "*"
  "@mui/styled-engine@*":
    dependencies:
      "@emotion/styled": "*"
  "@graphql-tools/code-file-loader@*":
    dependencies:
      "ts-node": "*"
